package ob.debitos.simp.utilitario;

import java.util.List;

import javax.servlet.ServletOutputStream;
import javax.servlet.http.HttpServletResponse;

import org.apache.poi.xssf.streaming.SXSSFWorkbook;

import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.util.CellRangeAddress;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.hssf.util.HSSFColor;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellStyle;
import org.apache.poi.ss.usermodel.FillPatternType;
import org.apache.poi.ss.usermodel.Font;
import org.apache.poi.ss.usermodel.HorizontalAlignment;
import org.apache.poi.ss.usermodel.IndexedColors;

import ob.debitos.simp.model.consulta.movimiento.TxnsSwDmpLogDetallado;

import java.io.IOException;

public class SwDmpLogDetalladoExcelExporter 
{
    private SXSSFWorkbook woorbook;
    private Sheet sheet;
    
    public SwDmpLogDetalladoExcelExporter() {
        woorbook = new SXSSFWorkbook();
        sheet = woorbook.createSheet("SwDmpLogDetallado");
    }
    
    private void writeHeaderRow() 
    {
        sheet.createFreezePane(2, 2);
        sheet.setAutoFilter(new CellRangeAddress(1, 1, 1, 82));
        Row row = null;
        Cell cell = null;
        Font font = woorbook.createFont();
        font.setColor(HSSFColor.WHITE.index);
        font.setBold(true);
        font.setFontName("Segoe UI");
        CellStyle styleCells = woorbook.createCellStyle();
        styleCells.setFillForegroundColor(IndexedColors.DARK_BLUE.getIndex());
        styleCells.setFillPattern(FillPatternType.SOLID_FOREGROUND);
        styleCells.setAlignment(HorizontalAlignment.CENTER);
        styleCells.setFont(font);
        row = sheet.createRow(1);
        cell = row.createCell(1);
        cell.setCellValue("Message Type");
        cell.setCellStyle(styleCells);
        cell = row.createCell(2);
        cell.setCellValue("Ind Store Forward");
        cell.setCellStyle(styleCells);
        cell = row.createCell(3);
        cell.setCellValue("Account Number");
        cell.setCellStyle(styleCells);
        cell = row.createCell(4);
        cell.setCellValue("Processing Code");
        cell.setCellStyle(styleCells);
        cell = row.createCell(5);
        cell.setCellValue("Transaction Currency");
        cell.setCellStyle(styleCells);
        cell = row.createCell(6);
        cell.setCellValue("Transaction Amount");
        cell.setCellStyle(styleCells);
        cell = row.createCell(7);
        cell.setCellValue("Settlement Currency");
        cell.setCellStyle(styleCells);
        cell = row.createCell(8);
        cell.setCellValue("Settlement Amount");
        cell.setCellStyle(styleCells);
        cell = row.createCell(9);
        cell.setCellValue("Billing Currency");
        cell.setCellStyle(styleCells);
        cell = row.createCell(10);
        cell.setCellValue("Card Issuer Amount");
        cell.setCellStyle(styleCells);
        cell = row.createCell(11);
        cell.setCellValue("Transmission Date");
        cell.setCellStyle(styleCells);
        cell = row.createCell(12);
        cell.setCellValue("Transmission Time");
        cell.setCellStyle(styleCells);
        cell = row.createCell(13);
        cell.setCellValue("Conversion Rate Settlement");
        cell.setCellStyle(styleCells);
        cell = row.createCell(14);
        cell.setCellValue("Conversion Rate Billing");
        cell.setCellStyle(styleCells);
        cell = row.createCell(15);
        cell.setCellValue("TraceNumber");
        cell.setCellStyle(styleCells);
        cell = row.createCell(16);
        cell.setCellValue("Local Transaction Time");
        cell.setCellStyle(styleCells);
        cell = row.createCell(17);
        cell.setCellValue("Local Transaction Date");
        cell.setCellStyle(styleCells);
        cell = row.createCell(18);
        cell.setCellValue("Expiry Date");
        cell.setCellStyle(styleCells);
        cell = row.createCell(19);
        cell.setCellValue("Setllement Date");
        cell.setCellStyle(styleCells);
        cell = row.createCell(20);
        cell.setCellValue("Conversion Date");
        cell.setCellStyle(styleCells);
        cell = row.createCell(21);
        cell.setCellValue("Capture Date");
        cell.setCellStyle(styleCells);
        cell = row.createCell(22);
        cell.setCellValue("Merchant Type");
        cell.setCellStyle(styleCells);
        cell = row.createCell(23);
        cell.setCellValue("Pos Entry Mode");
        cell.setCellStyle(styleCells);
        cell = row.createCell(24);
        cell.setCellValue("Network Identifier");
        cell.setCellStyle(styleCells);
        cell = row.createCell(25);
        cell.setCellValue("Pos Condition Code");
        cell.setCellStyle(styleCells);
        cell = row.createCell(26);
        cell.setCellValue("Sett Amount Transaction Fee");
        cell.setCellStyle(styleCells);
        cell = row.createCell(27);
        cell.setCellValue("Sett Amount Processing Fee");
        cell.setCellStyle(styleCells);
        cell = row.createCell(28);
        cell.setCellValue("Acquiring Institution");
        cell.setCellStyle(styleCells);
        cell = row.createCell(29);
        cell.setCellValue("Forwarding Institution");
        cell.setCellStyle(styleCells);
        cell = row.createCell(30);
        cell.setCellValue("Track2 Data");
        cell.setCellStyle(styleCells);
        cell = row.createCell(31);
        cell.setCellValue("Reference Number");
        cell.setCellStyle(styleCells);
        cell = row.createCell(32);
        cell.setCellValue("Authorization Code");
        cell.setCellStyle(styleCells);
        cell = row.createCell(33);
        cell.setCellValue("Response Code");
        cell.setCellStyle(styleCells);
        cell = row.createCell(34);
        cell.setCellValue("Card Acceptor TermId");
        cell.setCellStyle(styleCells);
        cell = row.createCell(35);
        cell.setCellValue("Card Acceptor Location");
        cell.setCellStyle(styleCells);
        cell = row.createCell(36);
        cell.setCellValue("Original Message Type");
        cell.setCellStyle(styleCells);
        cell = row.createCell(37);
        cell.setCellValue("Original Trace Number");
        cell.setCellStyle(styleCells);
        cell = row.createCell(38);
        cell.setCellValue("Original Date");
        cell.setCellStyle(styleCells);
        cell = row.createCell(39);
        cell.setCellValue("Original Time");
        cell.setCellStyle(styleCells);
        cell = row.createCell(40);
        cell.setCellValue("Original Adquiring Inst");
        cell.setCellStyle(styleCells);
        cell = row.createCell(41);
        cell.setCellValue("Original Forwarding Inst");
        cell.setCellStyle(styleCells);
        cell = row.createCell(42);
        cell.setCellValue("Repla Transaction Amount");
        cell.setCellStyle(styleCells);
        cell = row.createCell(43);
        cell.setCellValue("Repla Settlement Amount");
        cell.setCellStyle(styleCells);
        cell = row.createCell(44);
        cell.setCellValue("Repla Transaction Fee");
        cell.setCellStyle(styleCells);
        cell = row.createCell(45);
        cell.setCellValue("Repla Settlement Fee");
        cell.setCellStyle(styleCells);
        cell = row.createCell(46);
        cell.setCellValue("Merchant");
        cell.setCellStyle(styleCells);
        cell = row.createCell(47);
        cell.setCellValue("Requesting Institution");
        cell.setCellStyle(styleCells);
        cell = row.createCell(48);
        cell.setCellValue("Account Identification1");
        cell.setCellStyle(styleCells);
        cell = row.createCell(49);
        cell.setCellValue("Account Identification2");
        cell.setCellStyle(styleCells);
        cell = row.createCell(50);
        cell.setCellValue("Card Category");
        cell.setCellStyle(styleCells);
        cell = row.createCell(51);
        cell.setCellValue("TierII");
        cell.setCellStyle(styleCells);
        cell = row.createCell(52);
        cell.setCellValue("Card Acceptor Id");
        cell.setCellStyle(styleCells);
        cell = row.createCell(53);
        cell.setCellValue("Concilia Autorizacion");
        cell.setCellStyle(styleCells);
        cell = row.createCell(54);
        cell.setCellValue("Concilia Log Contable");
        cell.setCellStyle(styleCells);
        cell = row.createCell(55);
        cell.setCellValue("Rol Transaccion");
        cell.setCellStyle(styleCells);
        cell = row.createCell(56);
        cell.setCellValue("Id Clase Servicio");
        cell.setCellStyle(styleCells);
        cell = row.createCell(57);
        cell.setCellValue("Id Membresía");
        cell.setCellStyle(styleCells);
        cell = row.createCell(58);
        cell.setCellValue("Id Origen");
        cell.setCellStyle(styleCells);
        cell = row.createCell(59);
        cell.setCellValue("Id Codigo Transacción");
        cell.setCellStyle(styleCells);
        cell = row.createCell(60);
        cell.setCellValue("Id Clase Transacción");
        cell.setCellStyle(styleCells);
        cell = row.createCell(61);
        cell.setCellValue("Fecha Proceso");
        cell.setCellStyle(styleCells);
        cell = row.createCell(62);
        cell.setCellValue("Id Cliente");
        cell.setCellStyle(styleCells);
        cell = row.createCell(63);
        cell.setCellValue("Id Empresa");
        cell.setCellStyle(styleCells);
        cell = row.createCell(64);
        cell.setCellValue("Id Proceso");
        cell.setCellStyle(styleCells);
        cell = row.createCell(65);
        cell.setCellValue("Id Canal");
        cell.setCellStyle(styleCells);
        cell = row.createCell(66);
        cell.setCellValue("Id BIN");
        cell.setCellStyle(styleCells);
        cell = row.createCell(67);
        cell.setCellValue("Cuenta From");
        cell.setCellStyle(styleCells);
        cell = row.createCell(68);
        cell.setCellValue("Cuenta To");
        cell.setCellStyle(styleCells);
        cell = row.createCell(69);
        cell.setCellValue("Numero Documento");
        cell.setCellStyle(styleCells);
        cell = row.createCell(70);
        cell.setCellValue("Cuenta Cargo");
        cell.setCellStyle(styleCells);
        cell = row.createCell(71);
        cell.setCellValue("Cuenta Abono");
        cell.setCellStyle(styleCells);
        cell = row.createCell(72);
        cell.setCellValue("Codigo Analítico");
        cell.setCellStyle(styleCells);
        cell = row.createCell(73);
        cell.setCellValue("Contab Fondos");
        cell.setCellStyle(styleCells);
        cell = row.createCell(74);
        cell.setCellValue("Id ATM");
        cell.setCellStyle(styleCells);
        cell = row.createCell(75);
        cell.setCellValue("Fecha Concilia Log");
        cell.setCellStyle(styleCells);
        cell = row.createCell(76);
        cell.setCellValue("Id Sub BIN");
        cell.setCellStyle(styleCells);
        cell = row.createCell(77);
        cell.setCellValue("Id Institución");
        cell.setCellStyle(styleCells);
        cell = row.createCell(78);
        cell.setCellValue("PAN Entry Mode");
        cell.setCellStyle(styleCells);
        cell = row.createCell(79);
        cell.setCellValue("PIN Entry Capability");
        cell.setCellStyle(styleCells);
        cell = row.createCell(80);
        cell.setCellValue("Institucion Emisora");
        cell.setCellStyle(styleCells);
        cell = row.createCell(81);
        cell.setCellValue("Institucion Receptora");
        cell.setCellStyle(styleCells);
        cell = row.createCell(82);
        cell.setCellValue("Código Seguimiento");
        cell.setCellStyle(styleCells);
    }
    
    private void writeDataRows(List<TxnsSwDmpLogDetallado> listTxnsSwDmpLogDetallado)
    {
        Font font = woorbook.createFont();
        font.setFontName("Segoe UI");
        CellStyle estiloBordes = ExportacionUtil.obtenerEstiloBordes(woorbook);
        estiloBordes.setFont(font);
        CellStyle estiloBordeFecha = ExportacionUtil.obtenerEstiloBordeFecha(woorbook);
        estiloBordeFecha.setDataFormat(woorbook.createDataFormat().getFormat("dd/MM/yyyy"));
        estiloBordeFecha.setFont(font);
        CellStyle estiloBordeDecimal = ExportacionUtil.obtenerEstiloBorderDecimal(woorbook);
        estiloBordeDecimal.setDataFormat(woorbook.createDataFormat().getFormat("0.0000"));
        estiloBordeDecimal.setFont(font);
        int rowCount = 2;
        if(listTxnsSwDmpLogDetallado.size() > 0) {
            for(TxnsSwDmpLogDetallado txnsSwDmpLogDetallado : listTxnsSwDmpLogDetallado) {
                Row row = sheet.createRow(rowCount++);
                Cell cell = row.createCell(1);
                cell.setCellStyle(estiloBordes);
                cell.setCellValue(txnsSwDmpLogDetallado.getVMessageType() == null ? "-" : txnsSwDmpLogDetallado.getVMessageType());
                cell = row.createCell(2);
                cell.setCellStyle(estiloBordes);
                cell.setCellValue(txnsSwDmpLogDetallado.getVIndStoreForward() == null ? "-" : txnsSwDmpLogDetallado.getVIndStoreForward());
                cell = row.createCell(3);
                cell.setCellStyle(estiloBordes);
                cell.setCellValue(txnsSwDmpLogDetallado.getVAccountNumber() == null ? "-" : maskNumber(txnsSwDmpLogDetallado.getVAccountNumber(), "######******####"));
                cell = row.createCell(4);
                cell.setCellStyle(estiloBordes);
                cell.setCellValue(txnsSwDmpLogDetallado.getVProcessingCode() == null ? "-" : txnsSwDmpLogDetallado.getVProcessingCode());
                cell = row.createCell(5);
                cell.setCellStyle(estiloBordes);
                cell.setCellValue(txnsSwDmpLogDetallado.getNTransactionCurrency());
                cell = row.createCell(6);
                cell.setCellStyle(estiloBordeDecimal);
                cell.setCellValue(txnsSwDmpLogDetallado.getNTransactionAmount());
                cell = row.createCell(7);
                cell.setCellStyle(estiloBordes);
                cell.setCellValue(txnsSwDmpLogDetallado.getNSettlementCurrency());
                cell = row.createCell(8);
                cell.setCellStyle(estiloBordeDecimal);
                cell.setCellValue(txnsSwDmpLogDetallado.getNSettlementAmount());
                cell = row.createCell(9);
                cell.setCellStyle(estiloBordes);
                cell.setCellValue(txnsSwDmpLogDetallado.getNBillingCurrency());
                cell = row.createCell(10);
                cell.setCellStyle(estiloBordeDecimal);
                cell.setCellValue(txnsSwDmpLogDetallado.getNCardIssuerAmount());
                cell = row.createCell(11);
                cell.setCellStyle(estiloBordeFecha);
                cell.setCellValue(txnsSwDmpLogDetallado.getDTransmissionDate() == null ? "-" : txnsSwDmpLogDetallado.getDTransmissionDate());
                cell = row.createCell(12);
                cell.setCellStyle(estiloBordes);
                cell.setCellValue(txnsSwDmpLogDetallado.getVTransmissionTime() == null ? "-" : txnsSwDmpLogDetallado.getVTransmissionTime());
                cell = row.createCell(13);
                cell.setCellStyle(estiloBordes);
                cell.setCellValue(txnsSwDmpLogDetallado.getNConversionRateSettlement());
                cell = row.createCell(14);
                cell.setCellStyle(estiloBordes);
                cell.setCellValue(txnsSwDmpLogDetallado.getNConversionRateBilling());
                cell = row.createCell(15);
                cell.setCellStyle(estiloBordes);
                cell.setCellValue(txnsSwDmpLogDetallado.getVTraceNumber() == null ? "-" : txnsSwDmpLogDetallado.getVTraceNumber());
                cell = row.createCell(16);
                cell.setCellStyle(estiloBordes);
                cell.setCellValue(txnsSwDmpLogDetallado.getVLocalTransactionTime() == null ? "-" : txnsSwDmpLogDetallado.getVLocalTransactionTime());
                cell = row.createCell(17);
                cell.setCellStyle(estiloBordeFecha);
                cell.setCellValue(txnsSwDmpLogDetallado.getDLocalTransactionDate() == null ? "-" : txnsSwDmpLogDetallado.getDLocalTransactionDate());
                cell = row.createCell(18);
                cell.setCellStyle(estiloBordes);
                cell.setCellValue("-");
                cell = row.createCell(19);
                cell.setCellStyle(estiloBordeFecha);
                cell.setCellValue(txnsSwDmpLogDetallado.getDSetllementDate());
                cell = row.createCell(20);
                cell.setCellStyle(estiloBordeFecha);
                cell.setCellValue(txnsSwDmpLogDetallado.getDConversionDate());
                cell = row.createCell(21);
                cell.setCellStyle(estiloBordeFecha);
                cell.setCellValue(txnsSwDmpLogDetallado.getDCaptureDate() == null ? "-" : txnsSwDmpLogDetallado.getDCaptureDate());
                cell = row.createCell(22);
                cell.setCellStyle(estiloBordes);
                cell.setCellValue(txnsSwDmpLogDetallado.getVMerchantType() == null ? "-" : txnsSwDmpLogDetallado.getVMerchantType());
                cell = row.createCell(23);
                cell.setCellStyle(estiloBordes);
                cell.setCellValue(txnsSwDmpLogDetallado.getVPosEntryMode() == null ? "-" : txnsSwDmpLogDetallado.getVPosEntryMode());
                cell = row.createCell(24);
                cell.setCellStyle(estiloBordes);
                cell.setCellValue(txnsSwDmpLogDetallado.getVNetworkIdentifier() == null ? "-" : txnsSwDmpLogDetallado.getVNetworkIdentifier());
                cell = row.createCell(25);
                cell.setCellStyle(estiloBordes);
                cell.setCellValue(txnsSwDmpLogDetallado.getVPosConditionCode() == null ? "-" : txnsSwDmpLogDetallado.getVPosConditionCode());
                cell = row.createCell(26);
                cell.setCellStyle(estiloBordeDecimal);
                cell.setCellValue(txnsSwDmpLogDetallado.getNSettAmountTransactionFee());
                cell = row.createCell(27);
                cell.setCellStyle(estiloBordeDecimal);
                cell.setCellValue(txnsSwDmpLogDetallado.getNSettAmountProcessingFee());
                cell = row.createCell(28);
                cell.setCellStyle(estiloBordes);
                cell.setCellValue(txnsSwDmpLogDetallado.getVAcquiringInstitution() == null ? "-" : txnsSwDmpLogDetallado.getVAcquiringInstitution());
                cell = row.createCell(29);
                cell.setCellStyle(estiloBordeDecimal);
                cell.setCellValue(txnsSwDmpLogDetallado.getVForwardingInstitution() == null ? "-" : txnsSwDmpLogDetallado.getVForwardingInstitution());
                cell = row.createCell(30);
                cell.setCellStyle(estiloBordes);
                cell.setCellValue(txnsSwDmpLogDetallado.getVTrack2Data() == null ? "-" : txnsSwDmpLogDetallado.getVTrack2Data());
                cell = row.createCell(31);
                cell.setCellStyle(estiloBordes);
                cell.setCellValue(txnsSwDmpLogDetallado.getVReferenceNumber() == null ? "-" : txnsSwDmpLogDetallado.getVReferenceNumber());
                cell = row.createCell(32);
                cell.setCellStyle(estiloBordes);
                cell.setCellValue(txnsSwDmpLogDetallado.getVAuthorizationCode() == null ? "-" : txnsSwDmpLogDetallado.getVAuthorizationCode());
                cell = row.createCell(33);
                cell.setCellStyle(estiloBordes);
                cell.setCellValue(txnsSwDmpLogDetallado.getNResponseCode() == null ? "-" : txnsSwDmpLogDetallado.getNResponseCode());
                cell = row.createCell(34);
                cell.setCellStyle(estiloBordes);
                cell.setCellValue(txnsSwDmpLogDetallado.getVCardAcceptorTermId() == null ? "-" : txnsSwDmpLogDetallado.getVCardAcceptorTermId());
                cell = row.createCell(35);
                cell.setCellStyle(estiloBordes);
                cell.setCellValue(txnsSwDmpLogDetallado.getVCardAcceptorLocation() == null ? "-" : txnsSwDmpLogDetallado.getVCardAcceptorLocation());
                cell = row.createCell(36);
                cell.setCellStyle(estiloBordes);
                cell.setCellValue(txnsSwDmpLogDetallado.getVOriginalMessageType() == null ? "-" : txnsSwDmpLogDetallado.getVOriginalMessageType());
                cell = row.createCell(37);
                cell.setCellStyle(estiloBordes);
                cell.setCellValue(txnsSwDmpLogDetallado.getVOriginalTraceNumber() == null ? "-" : txnsSwDmpLogDetallado.getVOriginalTraceNumber());
                cell = row.createCell(38);
                cell.setCellStyle(estiloBordeFecha);
                cell.setCellValue(txnsSwDmpLogDetallado.getDOriginalDate());
                cell = row.createCell(39);
                cell.setCellStyle(estiloBordes);
                cell.setCellValue(txnsSwDmpLogDetallado.getVOriginalTime() == null ? "-" : txnsSwDmpLogDetallado.getVOriginalTime());
                cell = row.createCell(40);
                cell.setCellStyle(estiloBordes);
                cell.setCellValue(txnsSwDmpLogDetallado.getVOriginalAdquiringInst() == null ? "-" : txnsSwDmpLogDetallado.getVOriginalAdquiringInst());
                cell = row.createCell(41);
                cell.setCellStyle(estiloBordes);
                cell.setCellValue(txnsSwDmpLogDetallado.getVOriginalForwardingInst() == null ? "-" : txnsSwDmpLogDetallado.getVOriginalForwardingInst());
                cell = row.createCell(42);
                cell.setCellStyle(estiloBordeDecimal);
                cell.setCellValue(txnsSwDmpLogDetallado.getNReplaTransactionAmount());
                cell = row.createCell(43);
                cell.setCellStyle(estiloBordeDecimal);
                cell.setCellValue(txnsSwDmpLogDetallado.getNReplaSettlementAmount());
                cell = row.createCell(44);
                cell.setCellStyle(estiloBordeDecimal);
                cell.setCellValue(txnsSwDmpLogDetallado.getNReplaTransactionFee());
                cell = row.createCell(45);
                cell.setCellStyle(estiloBordeDecimal);
                cell.setCellValue(txnsSwDmpLogDetallado.getNReplaSettlementFee());
                cell = row.createCell(46);
                cell.setCellStyle(estiloBordes);
                cell.setCellValue(txnsSwDmpLogDetallado.getVMerchant() == null ? "-" : txnsSwDmpLogDetallado.getVMerchant());
                cell = row.createCell(47);
                cell.setCellStyle(estiloBordes);
                cell.setCellValue(txnsSwDmpLogDetallado.getVRequestingInstitution() == null ? "-" : txnsSwDmpLogDetallado.getVRequestingInstitution());
                cell = row.createCell(48);
                cell.setCellStyle(estiloBordes);
                cell.setCellValue(txnsSwDmpLogDetallado.getVAccountIdentification1() == null ? "-" : txnsSwDmpLogDetallado.getVAccountIdentification1());
                cell = row.createCell(49);
                cell.setCellStyle(estiloBordes);
                cell.setCellValue(txnsSwDmpLogDetallado.getVAccountIdentification2() == null ? "-" : txnsSwDmpLogDetallado.getVAccountIdentification2());
                cell = row.createCell(50);
                cell.setCellStyle(estiloBordes);
                cell.setCellValue(txnsSwDmpLogDetallado.getVCardCategory() == null ? "-" : txnsSwDmpLogDetallado.getVCardCategory());
                cell = row.createCell(51);
                cell.setCellStyle(estiloBordes);
                cell.setCellValue(txnsSwDmpLogDetallado.getVTierII() == null ? "-" : txnsSwDmpLogDetallado.getVTierII());
                cell = row.createCell(52);
                cell.setCellStyle(estiloBordes);
                cell.setCellValue(txnsSwDmpLogDetallado.getVCardAcceptorId() == null ? "-" : txnsSwDmpLogDetallado.getVCardAcceptorId());
                cell = row.createCell(53);
                cell.setCellStyle(estiloBordes);
                cell.setCellValue(txnsSwDmpLogDetallado.getNConciliaAutorizacion());
                cell = row.createCell(54);
                cell.setCellStyle(estiloBordes);
                cell.setCellValue(txnsSwDmpLogDetallado.getNConciliaLogContable());
                cell = row.createCell(55);
                cell.setCellStyle(estiloBordes);
                cell.setCellValue(txnsSwDmpLogDetallado.getNRolTransaccion() == null ? "-" : txnsSwDmpLogDetallado.getNRolTransaccion());
                cell = row.createCell(56);
                cell.setCellStyle(estiloBordes);
                cell.setCellValue(txnsSwDmpLogDetallado.getCIdClaseServicio() == null ? "-" : txnsSwDmpLogDetallado.getCIdClaseServicio());
                cell = row.createCell(57);
                cell.setCellStyle(estiloBordes);
                cell.setCellValue(txnsSwDmpLogDetallado.getCIdMembresia() == null ? "-" : txnsSwDmpLogDetallado.getCIdMembresia());
                cell = row.createCell(58);
                cell.setCellStyle(estiloBordes);
                cell.setCellValue(txnsSwDmpLogDetallado.getNIdOrigen() == null ? "-" : txnsSwDmpLogDetallado.getNIdOrigen());
                cell = row.createCell(59);
                cell.setCellStyle(estiloBordes);
                cell.setCellValue(txnsSwDmpLogDetallado.getNIdCodigoTransaccion() == null ? "-" : txnsSwDmpLogDetallado.getNIdCodigoTransaccion());
                cell = row.createCell(60);
                cell.setCellStyle(estiloBordes);
                cell.setCellValue(txnsSwDmpLogDetallado.getNIdClaseTransaccion() == null ? "-" : txnsSwDmpLogDetallado.getNIdClaseTransaccion());
                cell = row.createCell(61);
                cell.setCellStyle(estiloBordeFecha);
                cell.setCellValue(txnsSwDmpLogDetallado.getDFechaProceso());
                cell = row.createCell(62);
                cell.setCellStyle(estiloBordes);
                cell.setCellValue(txnsSwDmpLogDetallado.getVIdCliente() == null ? "-" : txnsSwDmpLogDetallado.getVIdCliente());
                cell = row.createCell(63);
                cell.setCellStyle(estiloBordes);
                cell.setCellValue(txnsSwDmpLogDetallado.getVIdEmpresa() == null ? "-" : txnsSwDmpLogDetallado.getVIdEmpresa());
                cell = row.createCell(64);
                cell.setCellStyle(estiloBordes);
                cell.setCellValue(txnsSwDmpLogDetallado.getVIdProceso() == null ? "-" : txnsSwDmpLogDetallado.getVIdProceso());
                cell = row.createCell(65);
                cell.setCellStyle(estiloBordes);
                cell.setCellValue(txnsSwDmpLogDetallado.getNIdCanal() == null ? "-" : txnsSwDmpLogDetallado.getNIdCanal());
                cell = row.createCell(66);
                cell.setCellStyle(estiloBordes);
                cell.setCellValue(txnsSwDmpLogDetallado.getVIdBIN() == null ? "-" : txnsSwDmpLogDetallado.getVIdBIN());
                cell = row.createCell(67);
                cell.setCellStyle(estiloBordes);
                cell.setCellValue(txnsSwDmpLogDetallado.getVCuentaFrom() == null ? "-" : txnsSwDmpLogDetallado.getVCuentaFrom());
                cell = row.createCell(68);
                cell.setCellStyle(estiloBordes);
                cell.setCellValue(txnsSwDmpLogDetallado.getVCuentaTo() == null ? "-" : txnsSwDmpLogDetallado.getVCuentaTo());
                cell = row.createCell(69);
                cell.setCellStyle(estiloBordes);
                cell.setCellValue(txnsSwDmpLogDetallado.getVNumeroDocumento() == null ? "-" : txnsSwDmpLogDetallado.getVNumeroDocumento());
                cell = row.createCell(70);
                cell.setCellStyle(estiloBordes);
                cell.setCellValue(txnsSwDmpLogDetallado.getVCuentaCargo() == null ? "-" : txnsSwDmpLogDetallado.getVCuentaCargo());
                cell = row.createCell(71);
                cell.setCellStyle(estiloBordes);
                cell.setCellValue(txnsSwDmpLogDetallado.getVCuentaAbono() == null ? "-" : txnsSwDmpLogDetallado.getVCuentaAbono());
                cell = row.createCell(72);
                cell.setCellStyle(estiloBordes);
                cell.setCellValue(txnsSwDmpLogDetallado.getVCodigoAnalitico() == null ? "-" : txnsSwDmpLogDetallado.getVCodigoAnalitico());
                cell = row.createCell(73);
                cell.setCellStyle(estiloBordes);
                cell.setCellValue(txnsSwDmpLogDetallado.getNContabFondos());
                cell = row.createCell(74);
                cell.setCellStyle(estiloBordes);
                cell.setCellValue(txnsSwDmpLogDetallado.getNIdATM() == null ? "-" : txnsSwDmpLogDetallado.getNIdATM());
                cell = row.createCell(75);
                cell.setCellStyle(estiloBordeFecha);
                cell.setCellValue(txnsSwDmpLogDetallado.getDFechaConciliaLog() == null ? "-" : txnsSwDmpLogDetallado.getDFechaConciliaLog());
                cell = row.createCell(76);
                cell.setCellStyle(estiloBordes);
                cell.setCellValue(txnsSwDmpLogDetallado.getVIdSubBIN() == null ? "-" : txnsSwDmpLogDetallado.getVIdSubBIN());
                cell = row.createCell(77);
                cell.setCellStyle(estiloBordes);
                cell.setCellValue(txnsSwDmpLogDetallado.getNIdInstitucion() == null ? "-" : txnsSwDmpLogDetallado.getNIdInstitucion());
                cell = row.createCell(78);
                cell.setCellStyle(estiloBordes);
                cell.setCellValue(txnsSwDmpLogDetallado.getVPANEntryMode() == null ? "-" : txnsSwDmpLogDetallado.getVPANEntryMode());
                cell = row.createCell(79);
                cell.setCellStyle(estiloBordes);
                cell.setCellValue(txnsSwDmpLogDetallado.getVPINEntryCapability() == null ? "-" : txnsSwDmpLogDetallado.getVPINEntryCapability());
                cell = row.createCell(80);
                cell.setCellStyle(estiloBordes);
                cell.setCellValue(txnsSwDmpLogDetallado.getNInstitucionEmisora() == null ? "-" : txnsSwDmpLogDetallado.getNInstitucionEmisora());
                cell = row.createCell(81);
                cell.setCellStyle(estiloBordes);
                cell.setCellValue(txnsSwDmpLogDetallado.getNInstitucionReceptora() == null ? "-" : txnsSwDmpLogDetallado.getNInstitucionReceptora());
                cell = row.createCell(82);
                cell.setCellStyle(estiloBordes);
                cell.setCellValue(txnsSwDmpLogDetallado.getCodigoSeguimiento() == null ? "-" : txnsSwDmpLogDetallado.getCodigoSeguimiento());
            }
        }
    }
    
    public static String maskNumber(String number, String mask) {
       int index = 0;
       StringBuilder masked = new StringBuilder();
       for (int i = 0; i < mask.length(); i++) {
          char c = mask.charAt(i);
          if (c == '#') {
             masked.append(number.charAt(index));
             index++;
          } else if (c == '*') {
             masked.append(c);
             index++;
          } else {
             masked.append(c);
          }
       }
       return masked.toString();
    }
    
    public void export(HttpServletResponse response, List<TxnsSwDmpLogDetallado> listTxnsSwDmpLogDetallado) throws IOException
    {
        writeHeaderRow();
        writeDataRows(listTxnsSwDmpLogDetallado);
        ServletOutputStream outputStream = response.getOutputStream();
        woorbook.write(outputStream);
        woorbook.close();
        outputStream.close();
    }
}
